# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

def common_pods
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    pod 'Alamofire'
    pod 'DynamicJSON'
    pod 'Bond'
    pod 'Alamofire'
    pod 'FieryCrucible'
    pod 'Fabric'
    pod 'Crashlytics'
    
    pod 'NotificationBannerSwift'
end

target 'piggy-bank' do
  common_pods
end
  
target 'piggy-bank dev' do
  common_pods
end
